### ISSUE TITLE
Option to store http responses to file

### ISSUE THREAD

**Issue by vulnerablecodes** [projectdiscovery/katana#177]
An option to download all discovered files would be great. I know I can write a simple function to download all files via curl/wget etc, but having the option via katana itself would be ideal.

Based on - https://github.com/projectdiscovery/httpx/pull/848

```console
   -sr, -store-response              store http response to output directory
   -srd, -store-response-dir string  store http response to custom directory
```

**Comment by wdahlenburg** [comment]
@ehsandeep What are your thoughts on expanding this to allow for storing the HTTP request as well? Perhaps they are stored as a pair, rather than the same file?

The current PR seems to drop the request body, which is a fixable issue on it's own, but I'd consider to be a bug.
![image](https://user-images.githubusercontent.com/4451504/204664252-4c2f6f6b-75c1-49bf-9ffd-5dafc588dd1f.png)

The raw HTTP request is something that could be used by other tools, so long as it's "well-formed".

**Comment by ehsandeep** [comment]
@wdahlenburg thanks for pointing this and good point on the request, I will create a follow-up ticket as this can be extended to get more controls like `response`, `request + response`, `response body` and `response header`.

**Comment by wdahlenburg** [comment]
> @wdahlenburg thanks for pointing this and good point on the request, I will create a follow-up ticket as this can be extended to get more controls like `response`, `request + response`, `response body` and `response header`.

I wrote that comment before I messed with proxify, but is there a good reason for the output formats to be different between katana and proxify?
