### ISSUE TITLE
issue in headless option 

### ISSUE THREAD

**Issue by com0t** [projectdiscovery/katana#632]
Hi team,

I executed katana with `-hl` option, but after a long period of time, the chrome process did not stop, leading to a hang or freeze katana process.

![image](https://github.com/projectdiscovery/katana/assets/14344164/f1a2446a-b328-4396-bebe-3c9d3aa3f125)

**Comment by Mzack9999** [comment]
Please fill all the fields within the [new issue template](https://github.com/projectdiscovery/katana/issues/new?assignees=&labels=Type%3A+Bug&projects=&template=issue-report.md) otherwise it's impossible for us to investigate something we are unable to reproduce. I see you have also `httpx` running, are you using any headless option?
